services:
   api:
     entrypoint: ./entrypoint.test.sh
   website:
     entrypoint: ./entrypoint.test.sh
   test:
     container_name: getartway-tests
     image: oven/bun:1.1
     volumes:
       - .:/app
     working_dir: /app
     command: bun test
     environment:
       DATABASE_URL: postgresql://artway:artway@db:5432/artway-${NODE_ENV}?schema=public
     depends_on:
       db:
         condition: service_healthy
       api:
         condition: service_healthy
       website:
         condition: service_started
     networks:
       - default-${NODE_ENV}