x-env-vars: &shared-env-vars
  DATABASE_URL: postgresql://artway:artway@db:5432/artway-${NODE_ENV}?schema=public

services:
  db:
    container_name: getartway-db-${NODE_ENV}
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: artway-${NODE_ENV}
      POSTGRES_USER: artway
      POSTGRES_PASSWORD: artway
    volumes:
      - pg-data-${NODE_ENV}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - default-${NODE_ENV}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U artway -d artway-${NODE_ENV}"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    container_name: getartway-api-${NODE_ENV}
    restart: unless-stopped
    environment:
      <<: *shared-env-vars
      MAPBOX_PUBLIC_KEY: ${MAPBOX_PUBLIC_KEY}
      MAPBOX_SECRET_KEY: ${MAPBOX_SECRET_KEY}
      API_URL: ${API_URL}
    build:
      context: ./api
    ports:
      - "${API_PORT}:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default-${NODE_ENV}

  website:
    container_name: getartway-website-${NODE_ENV}
    restart: unless-stopped
    build:
      context: ./website
    ports:
      - "${WEBSITE_PORT}:3000"


volumes:
  pg-data-development:
  pg-data-production:
  pg-data-test:

networks:
  default-development:
  default-production:
  default-test: